### ISSUE TITLE
Support auto-closing PRs

### ISSUE THREAD

**Issue by ajdlinux** [ajdlinux/PRBot#1]
For repos where the bot has admin privileges (which is to say, not torvalds/linux!) we could automatically close the PR via the API.

This should be disabled by default and enabled by a configuration option, IMHO

**Comment by Electromaster232** [comment]
any progress on this yet @ajdlinux ?

**Comment by ajdlinux** [comment]
No, and right now I'm a bit too busy to look into this. Patches welcome!
